name: Realase
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  CreatePackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Compile it
        run: mvn -DskipTests package
      - run: "ls -la target/"
      - run: "mv  target/*.jar target/ecommerce.jar"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/ecommerce.jar"
          name: "My release"
          body: |
            ## My nice release
            here we go
     
